version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: 'cimg/node:19.1.0'

    steps:
      - checkout

      - run:
          name: Install and Test
          command: 'npm install && npm run coverage'

      - coveralls/upload