version: 2.1

orbs:
  coveralls: ergeon/coveralls-orb@1.2.0

jobs:
  build:
    docker:
      - image: 'circleci/node:17.0.0'

    steps:
      - checkout

      - run:
          name: Install and Test
          command: 'npm install && npm run coverage'

      - coveralls/upload